language: node_js
node_js:
  - "8"
  - "10"
cache:
  directories:
  - node_modules # NPM packages
script:
  # - npm run lint
  - npm test
notifications:
  email:
    on_success: never
    on_failure: change
